var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/apply/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__80788f8f._.js")
R.c("server/chunks/ssr/_07720ad9._.js")
R.c("server/chunks/ssr/_2f9ddbe9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__97276f91._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b057281._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__86f0dc2d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_apply_page_actions_a7796fdf.js")
R.m(24963)
module.exports=R.m(24963).exports
