var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/book/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__11b65992._.js")
R.c("server/chunks/ssr/_c93ec285._.js")
R.c("server/chunks/ssr/_07720ad9._.js")
R.c("server/chunks/ssr/node_modules_3e533b5a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__97276f91._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b057281._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__86f0dc2d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_book_page_actions_fd0dd983.js")
R.m(53230)
module.exports=R.m(53230).exports
